export const TEST_DISPATCH = 'TEST_DISPATCH'
export const GET_ERRORS = 'GET_ERRORS'
export const GET_USER = 'GET_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CHECK_IN_USER = 'CHECK_IN_USER'
export const GET_TICKET_TYPE = 'GET_TICKET_TYPE'
export const LOADING = 'LOADING'
export const CLEAR = 'CLEAR'
export const SET_BOOKING = 'SET_BOOKING'
export const GET_BOOKING_ERROR = 'GET_BOOKING_ERROR'
export const DONT_SHOW_ERROR = 'DONT_SHOW_ERROR'
export const REG_SPRITUAL = 'REG_SPRITUAL'
export const REG_CONTRACT = 'REG_CONTRACT'
export const DOT_LOADING = 'DOT_LOADING'
export const BOOKING_DAILY = 'BOOKING_DAILY'
export const BOOKING_CONTRACT = 'BOOKING_CONTRACT'
export const RF = 'RF'

export const BOOKING_SPRITUAL_BUS = 'BOOKING_SPRITUAL_BUS'

export const GET_TICKETS = 'GET_TICKETS'
export const GET_USERS = 'GET_USERS'

export const GET_BUSES = 'GET_BUSES'
export const REG_BUS = 'REG_BUS'

export const GET_TRAVELS = 'GET_TRAVELS'
export const GET_BUYIES = 'GET_BUYIES'
export const GET_SPRITUALS = 'GET_SPRITUALS'
export const REG_TRAVEL = 'REG_TRAVEL'
export const FALSE = 'FALSE'

export const REG_CONTRACT_BUS = 'REG_CONTRACT_BUS'
export const GET_CONTRACT_BUS = 'GET_CONTRACT_BUS'

export const GET_DAILY_DEPARTURE = 'GET_DAILY_DEPARTURE'
export const GET_DAILY_DESTINATION = 'GET_DAILY_DESTINATION'

export const GET_DAILY = 'GET_DAILY'
export const REG_DAILY = 'REG_DAILY'

export const NO_ERROR = 'NO_ERROR'
export const GET_CONTRACTS = 'GET_CONTRACTS'

export const NO_ADD = 'NO_ADD'

export const GET_FALSE = 'GET_FALSE'

export const TRY_ANOTHER = 'TRY_ANOTHER'

export const IS_ADMIN = 'IS_ADMIN'

export const CHECK_IN_BUSES = 'CHECK_IN_USES'
export const CHECK_IN_DAILY = 'CHECK_IN_DAILY'

export const BOOKING_DAILY_BUS = 'BOOKING_DAILY_BUS'
export const BC = 'BC'

export const NO_BOOKING = 'NO_BOOKING'

export const DELETE_SP = 'DELETE_SP'


export const GET_CONTRACT_DEPARTURE = 'GET_CONTRACT_DEPARTURE'
export const GET_CONTRACT_DESTINATION = 'GET_CONTRACT_DESTINATION'

export const REG_SPRITUAL_TRAVEL = 'REG_SPRITUAL_TRAVEL'

export const CHECK_IN_SPRITUAL_BUSES = 'CHECK_IN_SPRITUAL_BUSES'

export const NO_SPRITUAL_BOOKING = 'NO_SPRITUAL_BOOKING'

export const CHECK_IN_CONTRACT = 'CHECK_IN_CONTRACT'

export const DELETE_CONTRACT = 'DELETE_CONTRACT'

export const DELETE_DAILY = 'DELETE_DAILY'










